using System;
using System.IO;
using Xunit;
using LogiTrack.Models;

namespace LogiTrackTest;

public class InventoryItemTests
{
    [Fact]
    public void Constructor_SetsProperties()
    {
        var item = new InventoryItem("Widget", 10, "A1");
        // ItemId will be generated by the database on insert; new object should have default 0
        Assert.Equal(0, item.ItemId);
        Assert.Equal("Widget", item.Name);
        Assert.Equal(10, item.Quantity);
        Assert.Equal("A1", item.Location);
    }

    [Fact]
    public void ToString_ReturnsExpectedFormat()
    {
        var item = new InventoryItem("Gadget", 5, "B2");
        var s = item.ToString();
        // ItemId is default (0) until saved to DB, but ToString still includes it
        Assert.Contains("ItemId: 0", s);
        Assert.Contains("Name: Gadget", s);
        Assert.Contains("Quantity: 5", s);
        Assert.Contains("Location: B2", s);
    }

    [Fact]
    public void UpdateQuantity_ChangesQuantity()
    {
        var item = new InventoryItem("Part", 0, "C3");
        item.UpdateQuantity(42);
        Assert.Equal(42, item.Quantity);
    }

    [Fact]
    public void UpdateLocation_ChangesLocation()
    {
        var item = new InventoryItem("Bolt", 100, "D4");
        item.UpdateLocation("Z9");
        Assert.Equal("Z9", item.Location);
    }

    [Fact]
    public void DisplayInfo_WritesExpectedOutput()
    {
    var item = new InventoryItem("Pallet Jack", 12, "Warehouse A");

        using var sw = new StringWriter();
        var originalOut = Console.Out;
        try
        {
            Console.SetOut(sw);
            item.DisplayInfo();
        }
        finally
        {
            Console.SetOut(originalOut);
        }

        var output = sw.ToString().Trim();
        Assert.Equal("Item: Pallet Jack | Quantity: 12 | Location: Warehouse A", output);
    }
}
