using System;
using System.IO;
using Xunit;
using LogiTrack.Models;

namespace LogiTrackTest;

public class InventoryItemTests
{
    [Fact]
    public void Constructor_SetsProperties()
    {
        var item = new InventoryItem("Widget", 10, "A1", 3.99);
        // ItemId will be generated by the database on insert; new object should have default 0
        Assert.Equal(0, item.ItemId);
        Assert.Equal("Widget", item.Name);
        Assert.Equal(10, item.Quantity);
        Assert.Equal("A1", item.Location);
        Assert.Equal(3.99, item.Price);
    }

    [Fact]
    public void ToString_ReturnsExpectedFormat()
    {
        var item = new InventoryItem("Gadget", 5, "B2", 9.49);
        var s = item.ToString();
        // ItemId is default (0) until saved to DB, but ToString still includes it
        Assert.Contains("ItemId: 0", s);
        Assert.Contains("Name: Gadget", s);
        Assert.Contains("Quantity: 5", s);
        Assert.Contains("Location: B2", s);
        Assert.Contains("Price: 9.49", s);
    }

    /// <summary>
    /// Tests updating the quantity of the inventory item.
    /// </summary>
    [Fact]
    public void UpdateQuantity_ChangesQuantity()
    {
        var item = new InventoryItem("Part", 0, "C3", 1.99);
        item.UpdateQuantity(42);
        Assert.Equal(42, item.Quantity);
    }

    /// <summary>
    /// Tests updating the location of the inventory item.
    /// </summary>
    [Fact]
    public void UpdateLocation_ChangesLocation()
    {
        var item = new InventoryItem("Bolt", 100, "D4", 0.10);
        item.UpdateLocation("Z9");
        Assert.Equal("Z9", item.Location);
    }

    /// <summary>
    /// Tests updating the price of the inventory item.
    /// </summary>
    [Fact]
    public void UpdatePrice_ChangesPrice()
    {
        var item = new InventoryItem("Screw", 50, "E5", 0.05);
        item.UpdatePrice(0.07);
        Assert.Equal(0.07, item.Price);
    }

    /// <summary>
    /// Tests displaying the inventory item information.
    /// </summary>
    [Fact]
    public void DisplayInfo_WritesExpectedOutput()
    {
        var item = new InventoryItem("Pallet Jack", 12, "Warehouse A", 299.99);

        using var sw = new StringWriter();
        var originalOut = Console.Out;
        try
        {
            Console.SetOut(sw);
            item.DisplayInfo();
        }
        finally
        {
            Console.SetOut(originalOut);
        }

        var output = sw.ToString().Trim();
        Assert.Equal("Item: Pallet Jack | Quantity: 12 | Location: Warehouse A | Price: 299.99", output);
    }
}
