namespace LogiTrackTest;

using Xunit;
using LogiTrack.Models;


/// <summary>
/// Tests for the Order.
/// </summary>
public class OrderTests
{
    [Fact]
    public void Constructor_SetsProperties()
    {
        var order = new Order("Test Customer");
        // OrderId will be generated by the database on insert; new object should have default 0
        Assert.Equal(0, order.OrderId);
        Assert.Equal("Test Customer", order.CustomerName);
        Assert.Empty(order.OrderProducts);
        Assert.True((DateTime.Now - order.DatePlaced).TotalSeconds < 5); // DatePlaced is recent
    }
}